"""Simple pose estimator for pendulum images.

Trains a small CNN to predict pendulum angle from images.
Can be used to evaluate reconstruction/generation quality.

Usage:
    # Train
    python pose_estimator.py train --data-root flowmo/dataset/images --epochs 20
    
    # Evaluate on a directory of images
    python pose_estimator.py eval --checkpoint pose_estimator.pth --images path/to/images
    
    # Evaluate on images generated by the same generator as the dataset (generate_types)
    python pose_estimator.py eval-gen --checkpoint pose_estimator.pth --metadata flowmo/dataset/metadata.json --num-samples 500
"""

import argparse
import math
import os
import random

import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
from PIL import Image
from torch.utils.data import DataLoader, Dataset
import torchvision.transforms as T


class PoseEstimator(nn.Module):
    """Simple CNN for pose (angle) estimation."""
    
    def __init__(self):
        super().__init__()
        self.net = nn.Sequential(
            nn.Conv2d(3, 32, 4, 2, 1),    # 256 -> 128
            nn.BatchNorm2d(32),
            nn.ReLU(),
            nn.Conv2d(32, 64, 4, 2, 1),   # 128 -> 64
            nn.BatchNorm2d(64),
            nn.ReLU(),
            nn.Conv2d(64, 128, 4, 2, 1),  # 64 -> 32
            nn.BatchNorm2d(128),
            nn.ReLU(),
            nn.Conv2d(128, 256, 4, 2, 1), # 32 -> 16
            nn.BatchNorm2d(256),
            nn.ReLU(),
            nn.AdaptiveAvgPool2d(1),
            nn.Flatten(),
            nn.Linear(256, 64),
            nn.ReLU(),
            nn.Linear(64, 2),  # Output (sin θ, cos θ)
        )
    
    def forward(self, x):
        out = self.net(x)
        return F.normalize(out, dim=-1)  # Project to unit circle
    
    def get_angle(self, x):
        """Get angle in radians from image."""
        sincos = self.forward(x)
        return torch.atan2(sincos[:, 0], sincos[:, 1])
    
    def get_angle_degrees(self, x):
        """Get angle in degrees from image."""
        return self.get_angle(x) * 180 / math.pi


class PendulumDataset(Dataset):
    """Dataset for pendulum images with pose labels. Preloads all images into memory."""
    
    def __init__(self, data_root, split="train", train_ratio=0.9, seed=42, metadata_path=None):
        self.data_root = data_root
        
        # Load metadata for ground truth angles
        if metadata_path is None:
            metadata_path = os.path.join(os.path.dirname(data_root), "metadata.json")
        
        import json
        with open(metadata_path, 'r') as f:
            metadata = json.load(f)
        
        # Build filename -> angle mapping from metadata
        self.angle_map = {}
        for img_meta in metadata['images']:
            self.angle_map[img_meta['filename']] = img_meta['angle_degrees']
        
        # Collect all images
        all_files = []
        for fname in os.listdir(data_root):
            if fname.endswith(('.png', '.jpg')) and fname in self.angle_map:
                parts = fname.replace('.png', '').replace('.jpg', '').split('_')
                if len(parts) == 2:
                    instance_id = int(parts[0])
                    pose_id = int(parts[1])
                    angle_deg = self.angle_map[fname]
                    all_files.append((fname, instance_id, pose_id, angle_deg))
        
        # Sort for reproducibility
        all_files.sort()
        
        # Split train/val
        random.seed(seed)
        random.shuffle(all_files)
        split_idx = int(len(all_files) * train_ratio)
        
        if split == "train":
            self.files = all_files[:split_idx]
        else:
            self.files = all_files[split_idx:]
        
        self.transform = T.Compose([
            T.ToTensor(),
            T.Normalize(mean=[0.5, 0.5, 0.5], std=[0.5, 0.5, 0.5]),  # -> [-1, 1]
        ])
        
        # Preload all images into memory
        print(f"Preloading {len(self.files)} images into memory...")
        self.images = []
        self.targets = []
        self.angles_rad = []
        self.pose_ids = []
        
        for fname, instance_id, pose_id, angle_deg in self.files:
            img_path = os.path.join(self.data_root, fname)
            img = Image.open(img_path).convert('RGB')
            img = self.transform(img)
            self.images.append(img)
            
            angle_rad = angle_deg * math.pi / 180
            target = torch.tensor([math.sin(angle_rad), math.cos(angle_rad)], dtype=torch.float32)
            self.targets.append(target)
            self.angles_rad.append(angle_rad)
            self.pose_ids.append(pose_id)
        
        # Stack for faster access
        self.images = torch.stack(self.images)
        self.targets = torch.stack(self.targets)
        self.angles_rad = torch.tensor(self.angles_rad, dtype=torch.float32)
        self.pose_ids = torch.tensor(self.pose_ids, dtype=torch.long)
        print(f"Done. Images shape: {self.images.shape}")
    
    def __len__(self):
        return len(self.images)
    
    def __getitem__(self, idx):
        return self.images[idx], self.targets[idx], self.angles_rad[idx], self.pose_ids[idx]


def train(args):
    device = torch.device(args.device if torch.cuda.is_available() else "cpu")
    print(f"Using device: {device}")
    
    # Datasets
    train_dataset = PendulumDataset(args.data_root, split="train")
    val_dataset = PendulumDataset(args.data_root, split="val")
    
    print(f"Train samples: {len(train_dataset)}")
    print(f"Val samples: {len(val_dataset)}")
    
    train_loader = DataLoader(train_dataset, batch_size=args.batch_size, shuffle=True, num_workers=0)
    val_loader = DataLoader(val_dataset, batch_size=args.batch_size, shuffle=False, num_workers=0)
    
    # Model
    model = PoseEstimator().to(device)
    optimizer = torch.optim.Adam(model.parameters(), lr=args.lr)
    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=args.epochs)
    
    best_val_error = float('inf')
    
    for epoch in range(args.epochs):
        # Train
        model.train()
        train_loss = 0
        for imgs, targets, _, _ in train_loader:
            imgs, targets = imgs.to(device), targets.to(device)
            
            preds = model(imgs)
            # Cosine similarity loss - better for unit vectors
            loss = 1 - F.cosine_similarity(preds, targets, dim=-1).mean()
            
            optimizer.zero_grad()
            loss.backward()
            optimizer.step()
            
            train_loss += loss.item()
        
        train_loss /= len(train_loader)
        
        # Validate
        model.eval()
        val_errors = []
        with torch.no_grad():
            for imgs, targets, angles_gt, _ in val_loader:
                imgs = imgs.to(device)
                angles_gt = angles_gt.to(device)
                
                angles_pred = model.get_angle(imgs)
                error_rad = torch.abs(angles_pred - angles_gt)
                error_deg = error_rad * 180 / math.pi
                val_errors.extend(error_deg.cpu().tolist())
        
        mean_error = np.mean(val_errors)
        
        print(f"Epoch {epoch+1}/{args.epochs} | Train Loss: {train_loss:.4f} | Val Error: {mean_error:.2f}°")
        
        scheduler.step()
        
        # Save best
        if mean_error < best_val_error:
            best_val_error = mean_error
            torch.save({
                'model_state_dict': model.state_dict(),
                'epoch': epoch,
                'val_error': mean_error,
            }, args.output)
            print(f"  Saved best model (error: {mean_error:.2f}°)")
    
    print(f"\nTraining complete. Best val error: {best_val_error:.2f}°")
    print(f"Model saved to: {args.output}")


def evaluate(args):
    """Evaluate pose estimator on a directory of images."""
    import json
    
    device = torch.device(args.device if torch.cuda.is_available() else "cpu")
    
    # Load model
    model = PoseEstimator().to(device)
    checkpoint = torch.load(args.checkpoint, map_location=device, weights_only=False)
    model.load_state_dict(checkpoint['model_state_dict'])
    model.eval()
    print(f"Loaded model from {args.checkpoint} (val error: {checkpoint.get('val_error', 'N/A')}°)")
    
    # Load metadata for ground truth angles if available
    angle_map = {}
    if args.metadata and os.path.exists(args.metadata):
        with open(args.metadata, 'r') as f:
            metadata = json.load(f)
        for img_meta in metadata['images']:
            angle_map[img_meta['filename']] = img_meta['angle_degrees']
        print(f"Loaded ground truth angles from metadata ({len(angle_map)} images)")
    
    transform = T.Compose([
        T.Resize(256),
        T.CenterCrop(256),
        T.ToTensor(),
        T.Normalize(mean=[0.5, 0.5, 0.5], std=[0.5, 0.5, 0.5]),
    ])
    
    # Process images
    results = []
    for fname in sorted(os.listdir(args.images)):
        if not fname.endswith(('.png', '.jpg')):
            continue
        
        img_path = os.path.join(args.images, fname)
        img = Image.open(img_path).convert('RGB')
        img_tensor = transform(img).unsqueeze(0).to(device)
        
        with torch.no_grad():
            angle_deg = model.get_angle_degrees(img_tensor).item()
        
        # Get ground truth from metadata or filename
        gt_angle = angle_map.get(fname)
        if gt_angle is None:
            # Fallback: try to extract from filename
            parts = fname.replace('.png', '').replace('.jpg', '').split('_')
            if len(parts) >= 2:
                try:
                    pose_id = int(parts[-1])
                    gt_angle = (pose_id / 199) * 180 - 90
                except ValueError:
                    pass
        
        results.append({
            'file': fname,
            'predicted_angle': angle_deg,
            'gt_angle': gt_angle,
        })
        
        if gt_angle is not None:
            error = abs(angle_deg - gt_angle)
            print(f"{fname}: pred={angle_deg:.1f}°, gt={gt_angle:.1f}°, error={error:.1f}°")
        else:
            print(f"{fname}: pred={angle_deg:.1f}°")
    
    # Summary
    errors = [abs(r['predicted_angle'] - r['gt_angle']) for r in results if r['gt_angle'] is not None]
    if errors:
        print(f"\nSummary: Mean error = {np.mean(errors):.2f}°, Std = {np.std(errors):.2f}°")
    
    return results


def evaluate_reconstruction(args):
    """Evaluate reconstruction quality using pose estimator.
    
    Compares original images to reconstructed/generated images.
    """
    device = torch.device(args.device if torch.cuda.is_available() else "cpu")
    
    # Load model
    model = PoseEstimator().to(device)
    checkpoint = torch.load(args.checkpoint, map_location=device, weights_only=False)
    model.load_state_dict(checkpoint['model_state_dict'])
    model.eval()
    
    transform = T.Compose([
        T.Resize(256),
        T.CenterCrop(256),
        T.ToTensor(),
        T.Normalize(mean=[0.5, 0.5, 0.5], std=[0.5, 0.5, 0.5]),
    ])
    
    def get_angle(img_path):
        img = Image.open(img_path).convert('RGB')
        img_tensor = transform(img).unsqueeze(0).to(device)
        with torch.no_grad():
            return model.get_angle_degrees(img_tensor).item()
    
    # Compare original vs reconstructed
    errors = []
    for fname in sorted(os.listdir(args.original)):
        if not fname.endswith(('.png', '.jpg')):
            continue
        
        orig_path = os.path.join(args.original, fname)
        recon_path = os.path.join(args.reconstructed, fname)
        
        if not os.path.exists(recon_path):
            continue
        
        orig_angle = get_angle(orig_path)
        recon_angle = get_angle(recon_path)
        error = abs(orig_angle - recon_angle)
        errors.append(error)
        
        print(f"{fname}: orig={orig_angle:.1f}°, recon={recon_angle:.1f}°, error={error:.1f}°")
    
    if errors:
        print(f"\nReconstruction Error: Mean = {np.mean(errors):.2f}°, Std = {np.std(errors):.2f}°")


def evaluate_on_generated(args):
    """Evaluate pose estimator on images generated by the same generator that created the dataset.
    
    Loads dataset config and pendulum types from metadata, uses generate_types.render_pendulum
    to render fresh images at random angles, then runs the pose estimator and reports error.
    """
    import json
    
    from generate_types import (
        PendulumTypeConfig,
        PendulumType,
        render_pendulum,
    )
    
    device = torch.device(args.device if torch.cuda.is_available() else "cpu")
    
    # Load metadata
    with open(args.metadata, "r") as f:
        metadata = json.load(f)
    
    # Reconstruct config (convert lists to tuples for dataclass)
    cfg = metadata["config"].copy()
    for key in (
        "background_color",
        "string_color",
        "body_width_range",
        "body_height_range",
        "string_length_range",
        "string_thickness_range",
        "angle_range",
        "weight_size_range",
        "weight_shapes",
    ):
        if key in cfg and isinstance(cfg[key], list):
            cfg[key] = tuple(cfg[key])
    config = PendulumTypeConfig(**cfg)
    
    # Reconstruct pendulum types
    pendulum_types = []
    for t in metadata["pendulum_types"]:
        t = t.copy()
        for k in ("body_color", "weight_color"):
            if k in t and isinstance(t[k], list):
                t[k] = tuple(t[k])
        pendulum_types.append(PendulumType(**t))
    
    print(f"Loaded {len(pendulum_types)} pendulum types from {args.metadata}")
    
    # Load pose estimator
    model = PoseEstimator().to(device)
    checkpoint = torch.load(args.checkpoint, map_location=device, weights_only=False)
    model.load_state_dict(checkpoint["model_state_dict"])
    model.eval()
    print(f"Loaded pose estimator from {args.checkpoint}")
    
    transform = T.Compose([
        T.Resize(config.image_size),
        T.CenterCrop(config.image_size),
        T.ToTensor(),
        T.Normalize(mean=[0.5, 0.5, 0.5], std=[0.5, 0.5, 0.5]),
    ])
    
    angle_min, angle_max = config.angle_range
    if args.seed is not None:
        random.seed(args.seed)
    
    errors = []
    generated_info = []
    
    for i in range(args.num_samples):
        ptype = random.choice(pendulum_types)
        angle_deg = random.uniform(angle_min, angle_max)
        
        img, _ = render_pendulum(ptype, angle_deg, config)
        
        img_tensor = transform(img).unsqueeze(0).to(device)
        with torch.no_grad():
            pred_deg = model.get_angle_degrees(img_tensor).item()
        
        error = abs(pred_deg - angle_deg)
        errors.append(error)
        generated_info.append((ptype.type_id, angle_deg, pred_deg, error))
        
        if args.verbose:
            print(f"  type={ptype.type_id:02d} gt={angle_deg:.1f}° pred={pred_deg:.1f}° error={error:.1f}°")
        
        if args.output_dir:
            os.makedirs(args.output_dir, exist_ok=True)
            fname = f"gen_{i:04d}_type{ptype.type_id:02d}_gt{angle_deg:.1f}.png"
            img.save(os.path.join(args.output_dir, fname))
    
    if args.output_dir:
        print(f"Saved {args.num_samples} generated images to {args.output_dir}")
    
    print(f"\nGenerated eval: {args.num_samples} samples")
    print(f"  Mean error: {np.mean(errors):.2f}°")
    print(f"  Std error:  {np.std(errors):.2f}°")
    print(f"  Max error:  {np.max(errors):.2f}°")


def main():
    parser = argparse.ArgumentParser(description="Pendulum Pose Estimator")
    subparsers = parser.add_subparsers(dest="command", required=True)
    
    # Train command
    train_parser = subparsers.add_parser("train", help="Train the pose estimator")
    train_parser.add_argument("--data-root", type=str, default="../flowmo/dataset/images",
                              help="Path to images directory")
    train_parser.add_argument("--epochs", type=int, default=20)
    train_parser.add_argument("--batch-size", type=int, default=64)
    train_parser.add_argument("--lr", type=float, default=3e-3)
    train_parser.add_argument("--device", type=str, default="cuda")
    train_parser.add_argument("--output", type=str, default="pose_estimator.pth")
    
    # Eval command
    eval_parser = subparsers.add_parser("eval", help="Evaluate on images")
    eval_parser.add_argument("--checkpoint", type=str, required=True)
    eval_parser.add_argument("--images", type=str, required=True,
                             help="Directory of images to evaluate")
    eval_parser.add_argument("--metadata", type=str, default=None,
                             help="Path to metadata.json for ground truth angles")
    eval_parser.add_argument("--device", type=str, default="cuda")
    
    # Reconstruction eval command
    recon_parser = subparsers.add_parser("eval-recon", help="Compare original vs reconstructed")
    recon_parser.add_argument("--checkpoint", type=str, required=True)
    recon_parser.add_argument("--original", type=str, required=True)
    recon_parser.add_argument("--reconstructed", type=str, required=True)
    recon_parser.add_argument("--device", type=str, default="cuda")
    
    # Eval on generator-produced images (same generator as dataset)
    gen_parser = subparsers.add_parser("eval-gen", help="Evaluate on images from dataset generator")
    gen_parser.add_argument("--checkpoint", type=str, required=True)
    gen_parser.add_argument("--metadata", type=str, required=True,
                            help="Path to metadata.json from the types dataset")
    gen_parser.add_argument("--num-samples", type=int, default=500)
    gen_parser.add_argument("--seed", type=int, default=None)
    gen_parser.add_argument("--output-dir", type=str, default=None,
                            help="If set, save generated images here")
    gen_parser.add_argument("--verbose", action="store_true")
    gen_parser.add_argument("--device", type=str, default="cuda")
    
    args = parser.parse_args()
    
    if args.command == "train":
        train(args)
    elif args.command == "eval":
        evaluate(args)
    elif args.command == "eval-recon":
        evaluate_reconstruction(args)
    elif args.command == "eval-gen":
        evaluate_on_generated(args)


if __name__ == "__main__":
    main()

